In [ ]:
import tensorflow as tf


아래 주어진 여섯 개 tensor를 사용하여 문제를 풀어주세요. <br>
문제 아래 빈 셀에 정답을 입력하시면 됩니다. <br>
(tensor 객체에 .numpy() 메소드를 사용하면 배열값만 꺼낼 수 있습니다.)

In [31]:
c1 = tf.constant(3)
c2 = tf.constant([1, 5])
c3 = tf.constant([[1, 2], [5, 6]])
c4 = tf.constant([[1, 2], [5, 6], [3, 4], [-1, 8]])
c5 = tf.constant([[10, 20, 30], [-1, -2 ,-3]])
c6 = tf.constant([[[1,2]], [[3,4]], [[5,6]]])

In [40]:
print('c1 =', c1)
print('c1.numpy() =', c1.numpy())

c1 = tf.Tensor(3, shape=(), dtype=int32)
c1.numpy() = 3


#### 덧셈: 'tf.add 함수' 혹은 '+ 연산자'를 사용

In [32]:
# 예시
print('- 예시')
result1 = tf.constant([1,2]) + tf.constant([1,2])
print('result1=', result1.numpy())
result2 = tf.add(tf.constant([1,2]), tf.constant([1,2]))
print('result2=', result2.numpy())

- 예시
result1= [2 4]
result2= [2 4]


1-1. c1, c2를 사용하여 [4, 8] 을 만드세요

1-2. c2, c3을 사용하여 [[ 2,  7], [ 6, 11]]를 만드세요.

1-3. c2, c4를 사용하여 [[ 2,  7], [ 6, 11], [ 4,  9], [ 0, 13]] 를 만드세요.

#### 곱셈(행렬곱 X): 'tf.multiply 함수' 혹은 '* 연산자'를 사용

In [13]:
print('- 예시')
result1 = tf.constant([1,2]) * tf.constant([1,2])
print('result1=', result1.numpy())
result2 = tf.multiply(tf.constant([1,2]), tf.constant([1,2]))
print('result2=', result2.numpy())

- 예시
result1= [1 4]
result2= [1 4]


2-1. c1, c2를 사용하여 [3, 15] 를 만드세요.

2-2. c2, c3를 사용하여 [[ 1, 10], [ 5, 30]] 를 만드세요.

2-3. c2, c4를 사용하여 [[ 1, 10], [ 5, 30], [ 3, 20], [-1, 40]] 를 만드세요.

#### 행렬곱: tf.matmul 함수 사용

3-1. c4와 c5의 행렬곱 연산을 수행하고 그 결과를 출력하세요.

3-2. c2의 차원을 증가시켜 c3과의 행렬곱 연산이 가능하도록 만들고, 차원을 증가시킨 c2와 c3의 행렬곱 연산을 수행하고 그 결과를 출력하세요. (차원 증가 함수는 tf.expand_dims 입니다. 아래 예시가 있습니다.)

In [18]:
print('axis=0 :\n', tf.expand_dims(tf.constant([1,2]), axis=0).numpy()) # [[1 2]]
print('\naxis=1 :\n', tf.expand_dims(tf.constant([1,2]), axis=1).numpy()) # [[1] [2]]
# -- axis=0은 첫 번째 차원 증가, axis=1은 두 번째 차원 증가, axis=2은 세 번째 차원 증가, ... 를 의미합니다.

axis=0 :
 [[1 2]]

axis=1 :
 [[1]
 [2]]


#### 평균: tf.reduce_mean

In [20]:
print('- 예시')
result = tf.reduce_mean(tf.constant([1,2,3,4,5])).numpy()
print('result=', result)

- 예시
result= 3


4-1. c2의 평균을 출력하세요

4-2. c3의 1)행 단위 mean 값과, 2)열 단위 mean 값을 출력하세요. <br><br>
axis 파라미터를 사용합니다. <br>
axis=0은 행의 차원을 reduce하여 mean을 반환하고, <br>
axis=1은 열의 차원을 reduce하여 mean을 반환합니다. <br>

#### 최대값: tf.reduce_max

In [22]:
print('- 예시')
result = tf.reduce_max(tf.constant([1,2,3,4,5])).numpy()
print('result=', result)

- 예시
result= 5


5-1. c5의 1)행 단위 max 값과, 2)열 단위 max 값을 출력하세요. <br><br>
axis 파라미터를 사용합니다. <br>
axis=0은 행의 차원을 reduce하여 max를 반환하고,  <br>
axis=1은 열의 차원을 reduce하여 max를 반환합니다. <br>


#### 차원 감소: tf.squeeze
차원 증가시키는 tf.expand_dims와 반대되는 기능을 합니다.

In [26]:
print('- 예시')
result1 = tf.squeeze(tf.constant([[[0], [1], [2]]])).numpy()
result2 = tf.squeeze(tf.constant([[[0], [1], [2]]]), axis=0).numpy()
result3 = tf.squeeze(tf.constant([[[0], [1], [2]]]), axis=2).numpy()
print('result1:\n', result1); print('\nresult2:\n', result2); print('\nresult3:\n', result3)

- 예시
result1:
 [0 1 2]

result2:
 [[0]
 [1]
 [2]]

result3:
 [[0 1 2]]


6-1. 현재 shape=(3, 1, 2)인 c6의 차원을 감소시켜 shape=(3, 2) 형태로 만드세요.

#### 행렬 형태 변형: tf.reshape

In [28]:
print('- 예시')
result = tf.reshape(tf.constant([[1,2,3],[4,5,6]]), [6]).numpy()
print('result=', result)

- 예시
result= [1 2 3 4 5 6]


7-1. c2를 reshape하여 [[1], [5]] 와 같이 만드세요.

7-2. c4를 reshape하여 [[1,2,5,6], [3,4,-1,8]] 와 같이 만드세요.

![python image2](https://thumbs.gfycat.com/CrispAnotherAlpineroadguidetigerbeetle-size_restricted.gif) <br>
<center>고생했습니다 ㅎㅎㅎ</center>